### ISSUE TITLE
SyntaxError at 1.0.0

### ISSUE THREAD

**Issue by drosi94** [jkyberneees/hydra-integration#3]
I have just updated to version 1.0.0 of hydra integration and when I run the project I get this error.

![1](https://user-images.githubusercontent.com/3253526/30788172-7b3807e2-a1a0-11e7-9d6e-ada6e35660f2.jpg)

While i try to debug this, I remove the trailing comma before the closing parentheses like this one and it worked.
![2](https://user-images.githubusercontent.com/3253526/30788171-7b296228-a1a0-11e7-9ca7-060b66685121.jpg)

I use node 7.9.0, npm 5.3.0 with typescript and gulp

The same trailing comma exist almost at all strategy files. I can PR the fix if it needs.

**Comment by jkyberneees** [comment]
Thanks for reporting @drosi94, I just pushed 1.0.1 with the fix, please check.
