### ISSUE TITLE
aws-serverless-express integration

### ISSUE THREAD

**Issue by TrejGun** [jkyberneees/hydra-integration#8]
thanks for this awesome lib!

I want to ask you to add integration for aws-serverless-express?

**Comment by jkyberneees** [comment]
Hi @TrejGun , thanks for reaching out. 
This module already supports `embedding` into existing apps. This means, you can actually use it on your existing solutions if they are based on the supported frameworks.

It would be as easy as this:
```js
await hydra.integration.sync(expressApp)
``` 
> You can see the full example here: https://github.com/jkyberneees/hydra-integration/blob/master/docs/HydraServiceFactory.md#embedding

Looking forward to hear from you again, 
Regards.

**Comment by TrejGun** [comment]
Thanks for you answer, i will try
